// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/InjectLiveScripts.tsx";
import * as $$$0 from "./components/FreshHead.tsx";
import * as $$$1 from "./components/GetStarted.tsx";
import * as $$$2 from "./components/Head.tsx";
import * as $$$3 from "./components/JsonPlaceholder.tsx";
import * as $$$4 from "./components/Layout.tsx";
import * as $$$$0 from "./loaders/jsonPlaceholder.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: { "./islands/InjectLiveScripts.tsx": $$0 },
  components: {
    "./components/FreshHead.tsx": $$$0,
    "./components/GetStarted.tsx": $$$1,
    "./components/Head.tsx": $$$2,
    "./components/JsonPlaceholder.tsx": $$$3,
    "./components/Layout.tsx": $$$4,
  },
  loaders: { "./loaders/jsonPlaceholder.ts": $$$$0 },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
