// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$$1 from "./sections/Hero.tsx";
import * as $$$$$$$2 from "./sections/ItWorks.tsx";
import * as $$$$$$$6 from "./sections/myHero.tsx";
import * as $$$$$$$3 from "./sections/ParagraphList.tsx";
import * as $$$$$$$7 from "./sections/sections/ItWorks.tsx";
import * as $$$$$$$4 from "./sections/SimpleTextList.tsx";
import * as $$$$$$$5 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/start/sections/Footer.tsx": $$$$$$$0,
    "deco-sites/start/sections/Hero.tsx": $$$$$$$1,
    "deco-sites/start/sections/ItWorks.tsx": $$$$$$$2,
    "deco-sites/start/sections/myHero.tsx": $$$$$$$6,
    "deco-sites/start/sections/ParagraphList.tsx": $$$$$$$3,
    "deco-sites/start/sections/sections/ItWorks.tsx": $$$$$$$7,
    "deco-sites/start/sections/SimpleTextList.tsx": $$$$$$$4,
    "deco-sites/start/sections/Theme/Theme.tsx": $$$$$$$5,
  },
  "apps": {
    "deco-sites/start/apps/decohub.ts": $$$$$$$$$$$$0,
    "deco-sites/start/apps/site.ts": $$$$$$$$$$$$1,
  },
  "name": "deco-sites/start",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
