// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$$1 from "./sections/ItWorks.tsx";
import * as $$$$$$$2 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Footer.tsx": $$$$$$$0,
    "site/sections/ItWorks.tsx": $$$$$$$1,
    "site/sections/Theme/Theme.tsx": $$$$$$$2,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
